# https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile
FROM nginx:latest

MAINTAINER meetbill <meetbill@163.com>
ENV REFRESHED_AT 2019-12-11

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./webroot/static /usr/share/nginx/html/static
COPY ./webroot/templates /usr/share/nginx/html/templates

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
